version: '3'

networks:
  full-web-application:
    driver: bridge

services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.5-31.0
    container_name: ldap
    ports:
      - "389:389"
    environment:
      STORAGE_DIR: /storage/fs1
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
    networks:
      - full-web-application

  db:
    image: dcm4che/postgres-dcm4chee:15.3-31
    container_name: db
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
    networks:
      - full-web-application

  arc:
    image: dcm4che/dcm4chee-arc-psql:5.31.0
    container_name: arc
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      WILDFLY_CHOWN: /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
    networks:
      - full-web-application

  web-app:
    build: 
        context: ./frontend
    image: ghcr.io/nas-ragde/reactjs_medical-imaging-fundamentals:latest
    ports:
      - "3001:3001"
    networks: 
      - full-web-application 
      
  backend:
    build: 
        context: ./backend 
    image: ghcr.io/nas-ragde/medical-imaging-fundamentals:latest
    ports: 
        - "8088:8088"
    networks:
      - full-web-application
    
  oviyam:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: Oviyam
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./Oviyam/oviyam2.war:/usr/local/tomcat/webapps/oviyam.war
    networks:
      - full-web-application

